#define IED_INDETERMINADO 							0
#define IED_ABIERTO											1
#define IED_CERRADO											2
#define IED_CNT_LIMIT										40
#define IED_DEST_DALI_I1								0x89
#define IED_DEST_DALI_I2								0x9B
#define IED_CMD_TIPO_DALI_I1_ABIERTO		0x2B
#define IED_CMD_TIPO_DALI_I1_CERRADO		0x2B
#define IED_CMD_TIPO_DALI_I2_ABIERTO		0x2C
#define IED_CMD_TIPO_DALI_I2_CERRADO		0x2C
#define IED_CMD_DALI_I1_ABIERTO					0x00
#define IED_CMD_DALI_I1_CERRADO					0x05
#define IED_CMD_DALI_I2_ABIERTO					0xE0
#define IED_CMD_DALI_I2_CERRADO					0xE2

#define IED_DEST_NORMALINK_I1									IED_DEST_DALI_I1	
#define IED_DEST_NORMALINK_I2									IED_DEST_DALI_I2
#define	IED_CMDH_NORMALINK_I1_ABIERTO					0x63
#define IED_CMDL_NORMALINK_I1_ABIERTO					0x01	
#define	IED_CMDH_NORMALINK_I1_CERRADO					0x63
#define IED_CMDL_NORMALINK_I1_CERRADO					0x06

#define	IED_CMDH_NORMALINK_I2_ABIERTO					0x64
#define IED_CMDL_NORMALINK_I2_ABIERTO					0x00
#define	IED_CMDH_NORMALINK_I2_CERRADO					0x64
#define IED_CMDL_NORMALINK_I2_CERRADO					0x02


void iD2DoTask(void);